#ifndef TLAYER_CTRL_H
#define TLAYER_CTRL_H

typedef enum {
	DOUBLE_VIDEO_LAYER_ERROR_NONE = 0,
	DOUBLE_VIDEO_LAYER_DISP_RECT_ERROR,
	DOUBLE_VIDEO_LAYER_WIDTH_AREA_ERROR,
	DOUBLE_VIDEO_LAYER_COORDINATE_ERROR,
	DOUBLE_VIDEO_LAYER_DISP_DISLOCATION_ERROR,
}DOUBLE_VIDEO_LAYER_ERROR_TYPE;


#endif  /*TLAYER_CTRL_H*/
